[toolchain]
channel = "1.95.0"
components = ["rustfmt", "clippy"]
targets = [
    # Linux
    "x86_64-unknown-linux-gnu",
    
    # macOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    
    # Windows
    "x86_64-pc-windows-msvc",
    
    # Android
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "x86_64-linux-android",
    "i686-linux-android",
    
    # iOS
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "x86_64-apple-ios",
    
    # WASM
    "wasm32-unknown-unknown",
]
