fn main() {
    // UniFFI scaffolding is generated by scmessenger-core
    // This build script can be used for additional platform-specific configuration
    println!("cargo:rerun-if-changed=build.rs");
}
