#!/bin/bash
# Script to delete merged branches from SCMessenger repository
# Generated by branch audit on 2026-02-12
# ONLY deletes branches that have been confirmed as merged via PRs

set -e

echo "==================================="
echo "SCMessenger Merged Branch Cleanup"
echo "==================================="
echo ""
echo "This script will delete branches that have been merged into main via PRs."
echo "All changes from these branches are safely in the main branch."
echo ""
echo "Branches to be deleted:"
echo "  1. claude/comprehensive-network-testing-bgVk8 (PR #10)"
echo "  2. claude/fix-dead-code-warnings-nP5ck (PR #7)"
echo "  3. claude/fix-docker-build-verification-5qr4k (PR #4)"
echo "  4. claude/fix-github-build-tests-bgVk8 (PRs #8, #9, #11)"
echo "  5. claude/fix-unused-variable-warning-uCK1E (PR #12)"
echo "  6. claude/gemini-ui-guide-LtFv9 (PR #3)"
echo "  7. claude/merge-control-api-to-main-5qr4k (PR #6)"
echo "  8. claude/setup-scmessenger-gcp-hOHGN (PRs #13-16)"
echo "  9. copilot/audit-repository-completeness (PR #2)"
echo " 10. copilot/merge-prs-and-address-comments (PR #20)"
echo " 11. copilot/fix-scm-send-encryption-error (PR #19)"
echo " 12. copilot/sub-pr-16 (PR #17)"
echo ""
echo "NOT deleted (have open PRs - review first):"
echo "  - copilot/fix-ci-build-test-actions (PR #21 - OPEN)"
echo "  - copilot/implement-remaining-development-gaps (PR #18 - OPEN)"
echo ""
read -p "Continue with deletion? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

echo ""
echo "Deleting merged branches from origin..."
echo ""

# Array of branches to delete
branches=(
    "claude/comprehensive-network-testing-bgVk8"
    "claude/fix-dead-code-warnings-nP5ck"
    "claude/fix-docker-build-verification-5qr4k"
    "claude/fix-github-build-tests-bgVk8"
    "claude/fix-unused-variable-warning-uCK1E"
    "claude/gemini-ui-guide-LtFv9"
    "claude/merge-control-api-to-main-5qr4k"
    "claude/setup-scmessenger-gcp-hOHGN"
    "copilot/audit-repository-completeness"
    "copilot/merge-prs-and-address-comments"
    "copilot/fix-scm-send-encryption-error"
    "copilot/sub-pr-16"
)

deleted_count=0
failed_count=0

for branch in "${branches[@]}"; do
    echo "Deleting: $branch"
    if git push origin --delete "$branch" 2>&1; then
        echo "  ✓ Deleted successfully"
        deleted_count=$((deleted_count + 1))
    else
        echo "  ✗ Failed to delete (may already be deleted)"
        failed_count=$((failed_count + 1))
    fi
    echo ""
done

echo "==================================="
echo "Summary:"
echo "  Deleted: $deleted_count"
echo "  Failed: $failed_count"
echo "==================================="
echo ""

if [ $deleted_count -gt 0 ]; then
    echo "Pruning local tracking branches..."
    git fetch --prune
    echo "✓ Local tracking branches pruned"
    echo ""
fi

echo "Cleanup complete!"
echo ""
echo "Note: To delete the audit branch itself (copilot/audit-branch-merges),"
echo "run this after PR #22 is merged:"
echo "  git push origin --delete copilot/audit-branch-merges"
